In [1]:
import numpy as np

# Scalar operations

This is simply done with the multiplication operator (`*`) in Python, where one of the objects is a scalar and the other is a Numpy array.

This is notated for a scalar $s$ and a matrix $A$ as:
$$C = sA$$

Scalar multiplication is commutative: $$C = sA = As$$

Create example arrays:

In [2]:
a = np.random.randint(0,9,(3))
b = np.random.randint(0,9,(2,4))

print('a = \n{}\n'.format(a))
print('b = \n{}\n'.format(b))

a = 
[0 6 2]

b = 
[[5 0 7 5]
 [6 7 0 1]]



Multiplication of each element in an array of any dimension is simply performed with the mulitplication symbol `*`:

In [3]:
s = 2
r_1 = s * a
r_2 = s * b

print('r_1 = \n{}\n'.format(r_1))
print('r_2 = \n{}\n'.format(r_2))

r_1 = 
[ 0 12  4]

r_2 = 
[[10  0 14 10]
 [12 14  0  2]]



# Operations on 1D arrays

Create example arrays:

In [4]:
a = np.random.randint(0,9,(4))
b = np.random.randint(0,9,(4))

print('a = \n{}\n'.format(a))
print('b = \n{}\n'.format(b))

a = 
[4 1 1 6]

b = 
[1 7 4 5]



## Inner product of two vectors

For two vectors $\boldsymbol{a}$ and $\boldsymbol{b}$, the inner (dot) product is the sum of the product of components. It is written as:

$$c = \sum_{i}a_ib_i$$

In matrix notation, this is written as:

$$c =
\begin{pmatrix}a_1, a_2, ..., a_n\end{pmatrix}
\begin{pmatrix}b_1\\b_2\\...\\b_n\end{pmatrix}
$$

**Method 1: `for` loop**

In [5]:
def inner_prod(a, b):
    
    total = 0
    for i in range(len(a)):
        total += a[i] * b[i]
    
    return total

inner_prod(a,b)

45

**Method 2: `np.dot()`**

In [6]:
np.dot(a,b)

45

**Method 3: `np.einsum()`**

In [7]:
np.einsum('i,i',a,b)

45

## Outer product of two vectors

For two vectors $\boldsymbol{a}$ and $\boldsymbol{b}$, the outer product is written in matrix notation as:

$$C = 
\begin{pmatrix}a_1\\a_2\\\vdots\\a_n\end{pmatrix}
\begin{pmatrix}b_1, b_2, \ldots, b_n\end{pmatrix} =
\begin{pmatrix}
a_1b_1 & a_1b_2 & \ldots  &  a_1b_n \\
a_2b_1 & \ldots & \ldots & \ldots             \\
\ldots & \ldots & \ldots & \ldots \\
a_nb_1 & \ldots & \ldots & a_nb_n
\end{pmatrix}
$$

**Method 1: `for` loops**

In [8]:
def outer_prod(a,b):
    c = np.empty((len(a), len(b)), dtype=a.dtype)
    
    for i in range(len(a)):
        for j in range(len(b)):
            c[i,j] = a[i] * b[j]
            
    return c

outer_prod(a,b)

array([[ 4, 28, 16, 20],
       [ 1,  7,  4,  5],
       [ 1,  7,  4,  5],
       [ 6, 42, 24, 30]])

**Method 2: `np.outer()`**

In [9]:
np.outer(a,b)

array([[ 4, 28, 16, 20],
       [ 1,  7,  4,  5],
       [ 1,  7,  4,  5],
       [ 6, 42, 24, 30]])

**Method 3: `np.einsum()`**

In [10]:
np.einsum('i,j->ij', a, b)

array([[ 4, 28, 16, 20],
       [ 1,  7,  4,  5],
       [ 1,  7,  4,  5],
       [ 6, 42, 24, 30]])

## Cross product of two vectors

Cross product is defined for 2 and 3-dimensional vectors. Create example arrays:

In [11]:
a = np.random.randint(0,9,(3))
b = np.random.randint(0,9,(3))

print('a = \n{}\n'.format(a))
print('b = \n{}\n'.format(b))

a = 
[8 4 3]

b = 
[7 3 0]



In [12]:
np.cross(a,b)

array([-9, 21, -4])

# Operations on 2D arrays

Create example arrays:

In [47]:
a = np.random.randint(0,9,(1,3))    # row vector
b = np.random.randint(0,9,(3,1))    # col vector
A = np.random.randint(0,9,(3,3))
B = np.random.randint(0,9,(3,3))

print('a = \n{}\n'.format(a))
print('b = \n{}\n'.format(b))
print('A = \n{}\n'.format(A))
print('B = \n{}\n'.format(B))

a = 
[[1 3 0]]

b = 
[[4]
 [7]
 [1]]

A = 
[[6 0 7]
 [1 7 4]
 [6 7 7]]

B = 
[[2 3 3]
 [0 3 2]
 [7 1 5]]



## Matrix product

Define a function using to compute the matrix product of two 2D arrays using nested for loops:

In [48]:
def mat_mult(a,b):
    
    # output array has same number of rows as a and same number of columns as b
    c = np.zeros((a.shape[0], b.shape[1]), dtype=a.dtype)
    
    for a_row in range(a.shape[0]):
    
        for b_col in range(b.shape[1]):

            for a_col in range(a.shape[1]):

                b_row = a_col                            
                c[a_row, b_col] += (a[a_row, a_col] * b[b_row, b_col])            
    
    return c

### Inner product of two vectors

**Method 1: `for` loops**

In [49]:
mat_mult(a,b)

array([[25]])

**Method 2: `np.dot()`**

In [50]:
np.dot(a,b)

array([[25]])

**Method 3: `np.einsum()`**

In [51]:
np.einsum('ij,jk',a,b)

array([[25]])

**Method 4: `np.matmul()` - `@`**

In [52]:
a @ b

array([[25]])

### Outer product of two vectors

**Method 1: `for` loops**

In [53]:
mat_mult(a.T,b.T)

array([[ 4,  7,  1],
       [12, 21,  3],
       [ 0,  0,  0]])

**Method 2: `np.dot()` and `np.outer()`**

In [54]:
np.dot(a.T,b.T)

array([[ 4,  7,  1],
       [12, 21,  3],
       [ 0,  0,  0]])

In [55]:
np.outer(a,b)

array([[ 4,  7,  1],
       [12, 21,  3],
       [ 0,  0,  0]])

**Method 3: `np.einsum()`**

In [56]:
np.einsum('ij,kl->jk',a,b)

array([[ 4,  7,  1],
       [12, 21,  3],
       [ 0,  0,  0]])

**Method 4: `np.matmul()` - `@`**

In [57]:
a.T @ b.T

array([[ 4,  7,  1],
       [12, 21,  3],
       [ 0,  0,  0]])

### Matrix product of two matrices

**Method 1: `for` loops**

In [58]:
mat_mult(A,B)

array([[61, 25, 53],
       [30, 28, 37],
       [61, 46, 67]])

**Method 2: `np.dot()`**

In [59]:
np.dot(A,B)

array([[61, 25, 53],
       [30, 28, 37],
       [61, 46, 67]])

**Method 3: `np.einsum()`**

In [60]:
np.einsum('ij,jk->ik',A,B)

array([[61, 25, 53],
       [30, 28, 37],
       [61, 46, 67]])

**Method 4: `np.matmul()` - `@`**

In [61]:
A @ B

array([[61, 25, 53],
       [30, 28, 37],
       [61, 46, 67]])

## Cross product of two vectors

`np.cross()` accepts 1D vectors, or row vectors represented as `1 x 3` arrays, but not column vectors represented as `3 x 1` arrays by default. We can modify the axis defining the input and output vectors however, which allows us to operate on column vectors represented as `3 x 1` arrays:

In [71]:
np.cross(a, b, axisb=0)

array([[ 3, -1, -5]])

## Hadamard product

In [72]:
A * B

array([[12,  0, 21],
       [ 0, 21,  8],
       [42,  7, 35]])

## Kronecker product

The outer product on two vectors can be generalised to 2D matrices. For a matrix $A$ with shape `n x m` and a matrix $B$ with shape `p x q`, the Knocker product produces a matrix with shape `np x mq`, and is written as:

$$
A \otimes B = 
\begin{pmatrix}
a_{11}B & \ldots & a_{1m}B & \\
\vdots & \ddots & \vdots & \\
a_{n1}B & \ldots & a_{nm}B & \\
\end{pmatrix}
$$

Write a function using for loops to perform the Kronecker product:

In [73]:
def kron_prod(a, b):
    
    b_nrows = b.shape[0]
    b_ncols = b.shape[1]
    
    c_shape = tuple([i*j for i, j in zip(a.shape, b.shape)])
    
    if a.dtype is b.dtype:
        c_dtype = a.dtype
    else:
        c_dtype = float
        
    c = np.empty(c_shape, dtype=c_dtype)
    
    for i_idx, i in enumerate(a):
        for j_idx, j in enumerate(i):
            sub_arr = j * b
            c[i_idx*b_nrows:(i_idx+1)*b_nrows, j_idx*b_ncols:(j_idx+1)*b_ncols] = sub_arr
    
    return c

**Method 1: `for` loops**

In [74]:
kron_prod(A,B)

array([[12, 18, 18,  0,  0,  0, 14, 21, 21],
       [ 0, 18, 12,  0,  0,  0,  0, 21, 14],
       [42,  6, 30,  0,  0,  0, 49,  7, 35],
       [ 2,  3,  3, 14, 21, 21,  8, 12, 12],
       [ 0,  3,  2,  0, 21, 14,  0, 12,  8],
       [ 7,  1,  5, 49,  7, 35, 28,  4, 20],
       [12, 18, 18, 14, 21, 21, 14, 21, 21],
       [ 0, 18, 12,  0, 21, 14,  0, 21, 14],
       [42,  6, 30, 49,  7, 35, 49,  7, 35]])

**Method 4: `np.kron()`**

In [75]:
np.kron(A,B)

array([[12, 18, 18,  0,  0,  0, 14, 21, 21],
       [ 0, 18, 12,  0,  0,  0,  0, 21, 14],
       [42,  6, 30,  0,  0,  0, 49,  7, 35],
       [ 2,  3,  3, 14, 21, 21,  8, 12, 12],
       [ 0,  3,  2,  0, 21, 14,  0, 12,  8],
       [ 7,  1,  5, 49,  7, 35, 28,  4, 20],
       [12, 18, 18, 14, 21, 21, 14, 21, 21],
       [ 0, 18, 12,  0, 21, 14,  0, 21, 14],
       [42,  6, 30, 49,  7, 35, 49,  7, 35]])

**Method 3: `np.einsum()`**

In [76]:
e = np.einsum('ij,kl->jikl',A,B)
E = np.concatenate(np.concatenate(e, axis=2), axis=0)
print(E)

[[12 18 18  0  0  0 14 21 21]
 [ 0 18 12  0  0  0  0 21 14]
 [42  6 30  0  0  0 49  7 35]
 [ 2  3  3 14 21 21  8 12 12]
 [ 0  3  2  0 21 14  0 12  8]
 [ 7  1  5 49  7 35 28  4 20]
 [12 18 18 14 21 21 14 21 21]
 [ 0 18 12  0 21 14  0 21 14]
 [42  6 30 49  7 35 49  7 35]]


# Transformations on row and column vectors

Numpy only has one type of one-dimensional array and so does not distinguish between row and column vectors. To distinguish, we represent a row vector as an `1 x N` 2D array and a column vector as a `N x 1` 2D array. By convention, column vectors are more widely used in physics.

A row vector could be specified like this:

In [79]:
np.array([[0,1,2]])

array([[0, 1, 2]])

... and a column vector could be specified like this:

In [80]:
np.array([[0],[1],[2]])

array([[0],
       [1],
       [2]])

... but this is more easily typed like this, where `T` is an alias for the Numpy `transpose()` method:

In [81]:
np.array([[0,1,2]]).T

array([[0],
       [1],
       [2]])

# Vectorised operations

## Transform a 2D array of column vectors

For a linear transformation matrix $A$ and an array of column vectors $v$, find the transformed vectors $u$:

$$u=Av$$

Create example arrays:

In [82]:
A = np.random.randint(-1,4,(3,3))
v = np.random.randint(0,9,(3,5))

print('A = \n{}\n'.format(A))
print('v = \n{}\n'.format(v))

A = 
[[2 2 1]
 [3 3 0]
 [2 3 1]]

v = 
[[7 6 4 7 7]
 [2 3 5 1 4]
 [3 7 0 7 0]]



In this case, Numpy's implicit broadcasting is sufficient to use both `np.dot()` and `np.matmul()`.

**Method 1: `np.dot()`**

In [83]:
np.dot(A,v)

array([[21, 25, 18, 23, 22],
       [27, 27, 27, 24, 33],
       [23, 28, 23, 24, 26]])

**Method 2: `np.einsum()`**

In [84]:
np.einsum('ij,jk->ik',A,v)

array([[21, 25, 18, 23, 22],
       [27, 27, 27, 24, 33],
       [23, 28, 23, 24, 26]])

**Method 3: `np.matmul()` - `@`**

In [85]:
A @ v

array([[21, 25, 18, 23, 22],
       [27, 27, 27, 24, 33],
       [23, 28, 23, 24, 26]])

## Transform a 3D array of column vectors

Creat example vectors array:

In [86]:
v = np.random.randint(0,9,(2,3,5))
print('v = \n{}\n'.format(v))

# Let's get the first layer for checking other methods:
u_0 = np.dot(A, v[0])
print('u_0 = \n{}\n'.format(u_0))

v = 
[[[5 0 7 0 3]
  [5 6 8 5 1]
  [6 7 7 1 4]]

 [[6 3 8 5 3]
  [1 4 4 1 5]
  [7 1 7 7 5]]]

u_0 = 
[[26 19 37 11 12]
 [30 18 45 15 12]
 [31 25 45 16 13]]



**Method 1: `np.dot()`**

In [87]:
np.dot(A,v).swapaxes(0,1)

array([[[26, 19, 37, 11, 12],
        [30, 18, 45, 15, 12],
        [31, 25, 45, 16, 13]],

       [[21, 15, 31, 19, 21],
        [21, 21, 36, 18, 24],
        [22, 19, 35, 20, 26]]])

For `np.dot()`, we have to swap axes to get the original shape.

**Method 2: `np.einsum()`**

In [88]:
np.einsum('ij,kjl->kil', A, v)

array([[[26, 19, 37, 11, 12],
        [30, 18, 45, 15, 12],
        [31, 25, 45, 16, 13]],

       [[21, 15, 31, 19, 21],
        [21, 21, 36, 18, 24],
        [22, 19, 35, 20, 26]]])

**Method 3: `np.matmul()` - `@`**

In [89]:
A @ v

array([[[26, 19, 37, 11, 12],
        [30, 18, 45, 15, 12],
        [31, 25, 45, 16, 13]],

       [[21, 15, 31, 19, 21],
        [21, 21, 36, 18, 24],
        [22, 19, 35, 20, 26]]])

`np.matmul()` and `np.einsum()` are clearly the cleaner solutions.

## Transform a 4D array of column vectors

Creat example vectors array:

In [90]:
v = np.random.randint(0,9,(2,2,3,5))
print('v = \n{}\n'.format(v))

# Let's get the first layer for checking other methods:
u_0 = np.dot(A, v[0,0])
print('u_0 = \n{}\n'.format(u_0))

v = 
[[[[2 2 5 5 4]
   [4 5 8 4 5]
   [0 7 2 0 4]]

  [[8 7 4 0 7]
   [8 8 7 1 0]
   [3 5 0 7 6]]]


 [[[5 7 7 1 5]
   [8 4 6 8 3]
   [0 8 5 5 6]]

  [[8 1 7 8 5]
   [4 6 2 8 1]
   [5 1 1 1 4]]]]

u_0 = 
[[12 21 28 18 22]
 [18 21 39 27 27]
 [16 26 36 22 27]]



**Method 1: `np.dot()`**

In [91]:
np.dot(A,v).swapaxes(0,2)

array([[[[12, 21, 28, 18, 22],
         [18, 21, 39, 27, 27],
         [16, 26, 36, 22, 27]],

        [[26, 30, 31, 23, 22],
         [39, 33, 39, 27, 24],
         [34, 34, 37, 31, 25]]],


       [[[35, 35, 22,  9, 20],
         [48, 45, 33,  3, 21],
         [43, 43, 29, 10, 20]],

        [[29, 15, 19, 33, 16],
         [36, 21, 27, 48, 18],
         [33, 21, 21, 41, 17]]]])

Again, for `np.dot()`, we have to swap axes to get the original shape.

**Method 2: `np.einsum()`**

In [92]:
np.einsum('ij,kljm->klim', A, v)

array([[[[12, 21, 28, 18, 22],
         [18, 21, 39, 27, 27],
         [16, 26, 36, 22, 27]],

        [[35, 35, 22,  9, 20],
         [48, 45, 33,  3, 21],
         [43, 43, 29, 10, 20]]],


       [[[26, 30, 31, 23, 22],
         [39, 33, 39, 27, 24],
         [34, 34, 37, 31, 25]],

        [[29, 15, 19, 33, 16],
         [36, 21, 27, 48, 18],
         [33, 21, 21, 41, 17]]]])

**Method 3: `np.matmul()` - `@`**

In [93]:
A @ v

array([[[[12, 21, 28, 18, 22],
         [18, 21, 39, 27, 27],
         [16, 26, 36, 22, 27]],

        [[35, 35, 22,  9, 20],
         [48, 45, 33,  3, 21],
         [43, 43, 29, 10, 20]]],


       [[[26, 30, 31, 23, 22],
         [39, 33, 39, 27, 24],
         [34, 34, 37, 31, 25]],

        [[29, 15, 19, 33, 16],
         [36, 21, 27, 48, 18],
         [33, 21, 21, 41, 17]]]])

Again, `np.matmul()` and `np.einsum()` are the best solutions. Where possible, `np.matmul()` is preferable since the syntax is so simple for this situation. From the `np.matmul()` docs: 

> If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

In [94]:
np.version.version

'1.14.3'

## Broadcasting the cross product (2D)

Create example arrays:

In [95]:
a = np.random.randint(-4,4,(3,1))
B = np.random.randint(-4,4,(3,5))

print('a = \n{}\n'.format(a))
print('B = \n{}\n'.format(B))

# Let's find the cross product of the first vector so we can check subsequent operations:
c = np.cross(a, B[:,0], axis=0)
print('c = \n{}\n'.format(c))

a = 
[[-3]
 [-4]
 [ 1]]

B = 
[[-1 -1  1 -2 -1]
 [-3  1  2 -3  0]
 [ 0 -2  1 -4 -2]]

c = 
[[ 3]
 [-1]
 [ 5]]



In [96]:
np.cross(a, B, axis=0)

array([[  3,   7,  -6,  19,   8],
       [ -1,  -7,   4, -14,  -7],
       [  5,  -7,  -2,   1,  -4]])

In [97]:
np.cross(B, a, axis=0)

array([[ -3,  -7,   6, -19,  -8],
       [  1,   7,  -4,  14,   7],
       [ -5,   7,   2,  -1,   4]])

## Broadcasting the cross product (3D)

Create example arrays:

In [98]:
a = np.random.randint(-4,4,(3,1))
B = np.random.randint(-4,4,(2,3,5))

print('a = \n{}\n'.format(a))
print('B = \n{}\n'.format(B))

# Let's find the cross product of the first vector so we can check subsequent operations:
c = np.cross(a, B[0,:,0], axis=0)
print('c = \n{}\n'.format(c))

a = 
[[-2]
 [-3]
 [ 0]]

B = 
[[[-4 -3  1  3  0]
  [ 3  0  2 -2  0]
  [-2  1  0  0  1]]

 [[-4  0  3  0  2]
  [-4 -4  3 -1 -4]
  [ 3 -4  1 -3 -3]]]

c = 
[[  6]
 [ -4]
 [-18]]



To broadcast correctly, we need to specify the axes for both input and output arrays:

In [99]:
np.cross(a, B, axisa=0, axisb=1, axisc=1)

array([[[  6,  -3,   0,   0,  -3],
        [ -4,   2,   0,   0,   2],
        [-18,  -9,  -1,  13,   0]],

       [[ -9,  12,  -3,   9,   9],
        [  6,  -8,   2,  -6,  -6],
        [ -4,   8,   3,   2,  14]]])

In [100]:
np.cross(B, a, axisa=1, axisb=0, axisc=1)

array([[[ -6,   3,   0,   0,   3],
        [  4,  -2,   0,   0,  -2],
        [ 18,   9,   1, -13,   0]],

       [[  9, -12,   3,  -9,  -9],
        [ -6,   8,  -2,   6,   6],
        [  4,  -8,  -3,  -2, -14]]])

Alternatively, we can fist ensure `a` and `B` have the same dimension. Then broadcasting will be correct without specifying different axes for input and output arrays:

In [101]:
a_1 = a[np.newaxis]
print('a_1 = \n{}\n'.format(a_1))

a_1 = 
[[[-2]
  [-3]
  [ 0]]]



In [102]:
np.cross(a_1, B, axis=1)

array([[[  6,  -3,   0,   0,  -3],
        [ -4,   2,   0,   0,   2],
        [-18,  -9,  -1,  13,   0]],

       [[ -9,  12,  -3,   9,   9],
        [  6,  -8,   2,  -6,  -6],
        [ -4,   8,   3,   2,  14]]])

## Column-wise dot product (2D)

Given two 2D arrays of column vectors of identical shape, find the dot product of each column of the first array with its correpsonding column in the second array.

Create example arrays:

In [103]:
v1 = np.random.randint(-2,4,(3,5))
v2 = np.random.randint(-2,4,(3,5))

print('v1 = \n{}\n'.format(v1))
print('v2 = \n{}\n'.format(v2))

v1 = 
[[-2  3 -2  3 -1]
 [-1  1  1  3  3]
 [ 2 -2  0  2  3]]

v2 = 
[[ 3  0 -1  2  2]
 [-2 -1  2  0 -2]
 [ 0  1  3  2  0]]



**Method 1: `*` and `np.sum()`**

In [104]:
np.sum(v1 * v2, axis=0)

array([-4, -3,  4, 10, -8])

**Method 2: `np.einsum()`**

In [105]:
np.einsum('ij,ij->j',v1,v2)

array([-4, -3,  4, 10, -8])

## Column-wise dot product (3D)

Given two 3D arrays of column vectors of identical shape, find the dot product of each column of the first array with its correpsonding column in the second array.

Create example arrays:

In [106]:
v1 = np.random.randint(-2,4,(2,3,5))
v2 = np.random.randint(-2,4,(2,3,5))

print('v1 = \n{}\n'.format(v1))
print('v2 = \n{}\n'.format(v2))

v1 = 
[[[ 2  2 -2  3 -2]
  [ 1 -1  0  1  3]
  [ 3  2 -2  2 -1]]

 [[-1  0  3  2  1]
  [ 1  1  0 -2  0]
  [ 1  0  0  3  2]]]

v2 = 
[[[ 3  1  0  3  1]
  [-2  0  1  2  2]
  [ 0 -2  1  2 -2]]

 [[ 1 -2 -2 -2 -2]
  [ 3 -2  2  1  2]
  [-2  2  0  2  2]]]



**Method 1: `*` and `np.sum()`**

In [107]:
np.sum(v1 * v2, axis=1)

array([[ 4, -2, -2, 15,  6],
       [ 0, -2, -6,  0,  2]])

**Method 2: `np.einsum()`**

In [108]:
np.einsum('ijk,ijk->ik',v1,v2)

array([[ 4, -2, -2, 15,  6],
       [ 0, -2, -6,  0,  2]])

## Column-wise cross product (2D)

Create example arrays:

In [109]:
A = np.random.randint(-4,4,(3,5))
B = np.random.randint(-4,4,(3,5))

print('A = \n{}\n'.format(A))
print('B = \n{}\n'.format(B))

# Let's find the cross product of the first vector so we can check subsequent operations:
c = np.cross(A[:,0:1], B[:,0:1], axis=0)
print('c = \n{}\n'.format(c))

A = 
[[-2  3 -1  2 -3]
 [ 0  2 -2  0 -3]
 [ 3  2  2 -2 -3]]

B = 
[[ 0  2 -2  1 -4]
 [ 0 -3 -4 -3 -1]
 [-2  1  0  1 -4]]

c = 
[[ 0]
 [-4]
 [ 0]]



In [110]:
np.cross(A, B, axis=0)

array([[  0,   8,   8,  -6,   9],
       [ -4,   1,  -4,  -4,   0],
       [  0, -13,   0,  -6,  -9]])

## Column-wise cross product (3D)

Create example arrays:

In [111]:
A = np.random.randint(-4,4,(2,3,5))
B = np.random.randint(-4,4,(2,3,5))

print('A = \n{}\n'.format(A))
print('B = \n{}\n'.format(B))

# Let's find the cross product of the first vector so we can check subsequent operations:
c = np.cross(A[0,:,0:1], B[0,:,0:1], axis=0)
print('c = \n{}\n'.format(c))

A = 
[[[-1  0  1  1 -1]
  [-1  0 -2  2  2]
  [-1  0 -3  1  1]]

 [[ 2 -4  0  1 -1]
  [-4  0  1  0  0]
  [ 2 -3 -1 -4  2]]]

B = 
[[[-3 -2  3 -4  2]
  [ 2  3  3 -1 -4]
  [-1 -1 -2  2  0]]

 [[-1 -3  3  2 -4]
  [ 0  2  0  1 -2]
  [-4  3  0 -2  1]]]

c = 
[[ 3]
 [ 2]
 [-5]]



In [112]:
np.cross(A, B, axis=1)

array([[[ 3,  0, 13,  5,  4],
        [ 2,  0, -7, -6,  2],
        [-5,  0,  9,  7,  0]],

       [[16,  6,  0,  4,  4],
        [ 6, 21, -3, -6, -7],
        [-4, -8, -3,  1,  2]]])

## Column pair dot product

Given a single array of shape `N x m x 2`, return a 1D array of length `N` whose elements are the dot products between length `m` column vector pairs.

Create example arrays:

In [113]:
p1 = np.random.randint(-2,4,(5,3,2))
print('p1 = \n{}\n'.format(p1))

p1 = 
[[[ 3  0]
  [ 3  2]
  [ 1  0]]

 [[ 0  0]
  [-1 -1]
  [ 0  0]]

 [[ 3 -2]
  [-1 -2]
  [ 2  0]]

 [[-2  1]
  [ 0  3]
  [-2 -2]]

 [[ 2 -2]
  [ 2  0]
  [ 2  1]]]



**Method 1: `*` and `np.sum()`**

In [114]:
np.sum(p1[:,:,0] * p1[:,:,1], axis=1)

array([ 6,  1, -4,  2, -2])

**Method 2: `np.einsum()`**

In [115]:
np.einsum('ij,ij->i',p1[:,:,0],p1[:,:,1])

array([ 6,  1, -4,  2, -2])

It probably makes more sense to keep this sort of data in an array of shape `2 x m x N` instead:

In [116]:
p2 = np.random.randint(-2,4,(2,3,5))
print('p2 = \n{}\n'.format(p2))

p2 = 
[[[ 3  0 -1  3 -1]
  [-2 -1  3 -1 -1]
  [ 1  2  3  3  0]]

 [[ 2 -2 -1 -2  0]
  [ 1  3 -1  0  3]
  [ 3  0 -2  0  0]]]



In [117]:
np.sum(p2[0] * p2[1], axis=0)

array([ 7, -3, -8, -6, -3])

In [118]:
np.einsum('ij,ij->j',p2[0],p2[1])

array([ 7, -3, -8, -6, -3])